/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerLoginRouteImport } from './routes/trainer-login'
import { Route as TrainerDashboardRouteImport } from './routes/trainer-dashboard'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrainerMembershipNumberRouteImport } from './routes/trainer.$membershipNumber'
import { Route as ExamsIdRouteImport } from './routes/exams.$id'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'
import { Route as CertificateCertNumberRouteImport } from './routes/certificate.$certNumber'
import { Route as AdminTrainersRouteImport } from './routes/admin.trainers'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminCreateExamRouteImport } from './routes/admin.create-exam'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ExamsIdTakeRouteImport } from './routes/exams.$id.take'
import { Route as ExamsIdResultRouteImport } from './routes/exams.$id.result'
import { Route as AdminTrainersTrainerIdRouteImport } from './routes/admin.trainers.$trainerId'
import { Route as AdminResultsAttemptIdRouteImport } from './routes/admin.results.$attemptId'
import { Route as AdminExamsNewRouteImport } from './routes/admin.exams.new'
import { Route as AdminTrainersTrainerIdSubscribersRouteImport } from './routes/admin.trainers.$trainerId.subscribers'

const TrainerLoginRoute = TrainerLoginRouteImport.update({
  id: '/trainer-login',
  path: '/trainer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerDashboardRoute = TrainerDashboardRouteImport.update({
  id: '/trainer-dashboard',
  path: '/trainer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerMembershipNumberRoute = TrainerMembershipNumberRouteImport.update({
  id: '/trainer/$membershipNumber',
  path: '/trainer/$membershipNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIdRoute = ExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExamsRoute,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCertNumberRoute = CertificateCertNumberRouteImport.update({
  id: '/certificate/$certNumber',
  path: '/certificate/$certNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainersRoute = AdminTrainersRouteImport.update({
  id: '/admin/trainers',
  path: '/admin/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/admin/exams',
  path: '/admin/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateExamRoute = AdminCreateExamRouteImport.update({
  id: '/admin/create-exam',
  path: '/admin/create-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/admin/certificates',
  path: '/admin/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIdTakeRoute = ExamsIdTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => ExamsIdRoute,
} as any)
const ExamsIdResultRoute = ExamsIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => ExamsIdRoute,
} as any)
const AdminTrainersTrainerIdRoute = AdminTrainersTrainerIdRouteImport.update({
  id: '/$trainerId',
  path: '/$trainerId',
  getParentRoute: () => AdminTrainersRoute,
} as any)
const AdminResultsAttemptIdRoute = AdminResultsAttemptIdRouteImport.update({
  id: '/admin/results/$attemptId',
  path: '/admin/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsNewRoute = AdminExamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminExamsRoute,
} as any)
const AdminTrainersTrainerIdSubscribersRoute =
  AdminTrainersTrainerIdSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AdminTrainersTrainerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/trainer-dashboard': typeof TrainerDashboardRoute
  '/trainer-login': typeof TrainerLoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/create-exam': typeof AdminCreateExamRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/trainers': typeof AdminTrainersRouteWithChildren
  '/certificate/$certNumber': typeof CertificateCertNumberRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/exams/$id': typeof ExamsIdRouteWithChildren
  '/trainer/$membershipNumber': typeof TrainerMembershipNumberRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/results/$attemptId': typeof AdminResultsAttemptIdRoute
  '/admin/trainers/$trainerId': typeof AdminTrainersTrainerIdRouteWithChildren
  '/exams/$id/result': typeof ExamsIdResultRoute
  '/exams/$id/take': typeof ExamsIdTakeRoute
  '/admin/trainers/$trainerId/subscribers': typeof AdminTrainersTrainerIdSubscribersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exams': typeof ExamsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/trainer-dashboard': typeof TrainerDashboardRoute
  '/trainer-login': typeof TrainerLoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/create-exam': typeof AdminCreateExamRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/trainers': typeof AdminTrainersRouteWithChildren
  '/certificate/$certNumber': typeof CertificateCertNumberRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/exams/$id': typeof ExamsIdRouteWithChildren
  '/trainer/$membershipNumber': typeof TrainerMembershipNumberRoute
  '/admin': typeof AdminIndexRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/results/$attemptId': typeof AdminResultsAttemptIdRoute
  '/admin/trainers/$trainerId': typeof AdminTrainersTrainerIdRouteWithChildren
  '/exams/$id/result': typeof ExamsIdResultRoute
  '/exams/$id/take': typeof ExamsIdTakeRoute
  '/admin/trainers/$trainerId/subscribers': typeof AdminTrainersTrainerIdSubscribersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exams': typeof ExamsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/trainer-dashboard': typeof TrainerDashboardRoute
  '/trainer-login': typeof TrainerLoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/create-exam': typeof AdminCreateExamRoute
  '/admin/exams': typeof AdminExamsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/trainers': typeof AdminTrainersRouteWithChildren
  '/certificate/$certNumber': typeof CertificateCertNumberRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/exams/$id': typeof ExamsIdRouteWithChildren
  '/trainer/$membershipNumber': typeof TrainerMembershipNumberRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/results/$attemptId': typeof AdminResultsAttemptIdRoute
  '/admin/trainers/$trainerId': typeof AdminTrainersTrainerIdRouteWithChildren
  '/exams/$id/result': typeof ExamsIdResultRoute
  '/exams/$id/take': typeof ExamsIdTakeRoute
  '/admin/trainers/$trainerId/subscribers': typeof AdminTrainersTrainerIdSubscribersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exams'
    | '/login'
    | '/register'
    | '/trainer-dashboard'
    | '/trainer-login'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/create-exam'
    | '/admin/exams'
    | '/admin/login'
    | '/admin/members'
    | '/admin/trainers'
    | '/certificate/$certNumber'
    | '/exam/$examId'
    | '/exams/$id'
    | '/trainer/$membershipNumber'
    | '/admin/'
    | '/admin/exams/new'
    | '/admin/results/$attemptId'
    | '/admin/trainers/$trainerId'
    | '/exams/$id/result'
    | '/exams/$id/take'
    | '/admin/trainers/$trainerId/subscribers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exams'
    | '/login'
    | '/register'
    | '/trainer-dashboard'
    | '/trainer-login'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/create-exam'
    | '/admin/exams'
    | '/admin/login'
    | '/admin/members'
    | '/admin/trainers'
    | '/certificate/$certNumber'
    | '/exam/$examId'
    | '/exams/$id'
    | '/trainer/$membershipNumber'
    | '/admin'
    | '/admin/exams/new'
    | '/admin/results/$attemptId'
    | '/admin/trainers/$trainerId'
    | '/exams/$id/result'
    | '/exams/$id/take'
    | '/admin/trainers/$trainerId/subscribers'
  id:
    | '__root__'
    | '/'
    | '/exams'
    | '/login'
    | '/register'
    | '/trainer-dashboard'
    | '/trainer-login'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/create-exam'
    | '/admin/exams'
    | '/admin/login'
    | '/admin/members'
    | '/admin/trainers'
    | '/certificate/$certNumber'
    | '/exam/$examId'
    | '/exams/$id'
    | '/trainer/$membershipNumber'
    | '/admin/'
    | '/admin/exams/new'
    | '/admin/results/$attemptId'
    | '/admin/trainers/$trainerId'
    | '/exams/$id/result'
    | '/exams/$id/take'
    | '/admin/trainers/$trainerId/subscribers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TrainerDashboardRoute: typeof TrainerDashboardRoute
  TrainerLoginRoute: typeof TrainerLoginRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCreateExamRoute: typeof AdminCreateExamRoute
  AdminExamsRoute: typeof AdminExamsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminTrainersRoute: typeof AdminTrainersRouteWithChildren
  CertificateCertNumberRoute: typeof CertificateCertNumberRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
  TrainerMembershipNumberRoute: typeof TrainerMembershipNumberRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminResultsAttemptIdRoute: typeof AdminResultsAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer-login': {
      id: '/trainer-login'
      path: '/trainer-login'
      fullPath: '/trainer-login'
      preLoaderRoute: typeof TrainerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer-dashboard': {
      id: '/trainer-dashboard'
      path: '/trainer-dashboard'
      fullPath: '/trainer-dashboard'
      preLoaderRoute: typeof TrainerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/$membershipNumber': {
      id: '/trainer/$membershipNumber'
      path: '/trainer/$membershipNumber'
      fullPath: '/trainer/$membershipNumber'
      preLoaderRoute: typeof TrainerMembershipNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$id': {
      id: '/exams/$id'
      path: '/$id'
      fullPath: '/exams/$id'
      preLoaderRoute: typeof ExamsIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$certNumber': {
      id: '/certificate/$certNumber'
      path: '/certificate/$certNumber'
      fullPath: '/certificate/$certNumber'
      preLoaderRoute: typeof CertificateCertNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainers': {
      id: '/admin/trainers'
      path: '/admin/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-exam': {
      id: '/admin/create-exam'
      path: '/admin/create-exam'
      fullPath: '/admin/create-exam'
      preLoaderRoute: typeof AdminCreateExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$id/take': {
      id: '/exams/$id/take'
      path: '/take'
      fullPath: '/exams/$id/take'
      preLoaderRoute: typeof ExamsIdTakeRouteImport
      parentRoute: typeof ExamsIdRoute
    }
    '/exams/$id/result': {
      id: '/exams/$id/result'
      path: '/result'
      fullPath: '/exams/$id/result'
      preLoaderRoute: typeof ExamsIdResultRouteImport
      parentRoute: typeof ExamsIdRoute
    }
    '/admin/trainers/$trainerId': {
      id: '/admin/trainers/$trainerId'
      path: '/$trainerId'
      fullPath: '/admin/trainers/$trainerId'
      preLoaderRoute: typeof AdminTrainersTrainerIdRouteImport
      parentRoute: typeof AdminTrainersRoute
    }
    '/admin/results/$attemptId': {
      id: '/admin/results/$attemptId'
      path: '/admin/results/$attemptId'
      fullPath: '/admin/results/$attemptId'
      preLoaderRoute: typeof AdminResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams/new': {
      id: '/admin/exams/new'
      path: '/new'
      fullPath: '/admin/exams/new'
      preLoaderRoute: typeof AdminExamsNewRouteImport
      parentRoute: typeof AdminExamsRoute
    }
    '/admin/trainers/$trainerId/subscribers': {
      id: '/admin/trainers/$trainerId/subscribers'
      path: '/subscribers'
      fullPath: '/admin/trainers/$trainerId/subscribers'
      preLoaderRoute: typeof AdminTrainersTrainerIdSubscribersRouteImport
      parentRoute: typeof AdminTrainersTrainerIdRoute
    }
  }
}

interface ExamsIdRouteChildren {
  ExamsIdResultRoute: typeof ExamsIdResultRoute
  ExamsIdTakeRoute: typeof ExamsIdTakeRoute
}

const ExamsIdRouteChildren: ExamsIdRouteChildren = {
  ExamsIdResultRoute: ExamsIdResultRoute,
  ExamsIdTakeRoute: ExamsIdTakeRoute,
}

const ExamsIdRouteWithChildren =
  ExamsIdRoute._addFileChildren(ExamsIdRouteChildren)

interface ExamsRouteChildren {
  ExamsIdRoute: typeof ExamsIdRouteWithChildren
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsIdRoute: ExamsIdRouteWithChildren,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

interface AdminExamsRouteChildren {
  AdminExamsNewRoute: typeof AdminExamsNewRoute
}

const AdminExamsRouteChildren: AdminExamsRouteChildren = {
  AdminExamsNewRoute: AdminExamsNewRoute,
}

const AdminExamsRouteWithChildren = AdminExamsRoute._addFileChildren(
  AdminExamsRouteChildren,
)

interface AdminTrainersTrainerIdRouteChildren {
  AdminTrainersTrainerIdSubscribersRoute: typeof AdminTrainersTrainerIdSubscribersRoute
}

const AdminTrainersTrainerIdRouteChildren: AdminTrainersTrainerIdRouteChildren =
  {
    AdminTrainersTrainerIdSubscribersRoute:
      AdminTrainersTrainerIdSubscribersRoute,
  }

const AdminTrainersTrainerIdRouteWithChildren =
  AdminTrainersTrainerIdRoute._addFileChildren(
    AdminTrainersTrainerIdRouteChildren,
  )

interface AdminTrainersRouteChildren {
  AdminTrainersTrainerIdRoute: typeof AdminTrainersTrainerIdRouteWithChildren
}

const AdminTrainersRouteChildren: AdminTrainersRouteChildren = {
  AdminTrainersTrainerIdRoute: AdminTrainersTrainerIdRouteWithChildren,
}

const AdminTrainersRouteWithChildren = AdminTrainersRoute._addFileChildren(
  AdminTrainersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamsRoute: ExamsRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TrainerDashboardRoute: TrainerDashboardRoute,
  TrainerLoginRoute: TrainerLoginRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCreateExamRoute: AdminCreateExamRoute,
  AdminExamsRoute: AdminExamsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminTrainersRoute: AdminTrainersRouteWithChildren,
  CertificateCertNumberRoute: CertificateCertNumberRoute,
  ExamExamIdRoute: ExamExamIdRoute,
  TrainerMembershipNumberRoute: TrainerMembershipNumberRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminResultsAttemptIdRoute: AdminResultsAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
